### ISSUE TITLE
Crash when config.toml doesn't have request and input

### ISSUE THREAD

**Issue by ledzep2** [ktr0731/evans#142]
I don't know why my config.toml ended up like this. And it crashes evans. I debugged a little and found out Request and Input are essential in Config. So I think it's a good idea to always check and set a default value to them after config is loaded.

```toml
[default]                                             
  package = ""                                        
  service = ""                                        
                                                      
[meta]                                                
  path = "~/.config/evans/config.toml"                
                                                      
[repl]                                                
  promptFormat = "{package}.{sevice}@{addr}:{port}"   
  reader = "stdin"                                    
  writer = "stdout"                                   
  errWriter = "stderr"                                
  coloredOutput = true                                
  showSplashText = true                               
  splashTextPath = ""                                 
                                                      
[env]                                                 
  inputPromptFormat = "{ancestor}{name} ({type}) => " 
  [env.request]                                       
                                                      
[server]                                              
  host = "127.0.0.1"                                  
  port = "50051"                                      
                                                      
[log]                                                 
  prefix = "[evans] "                                 
```
