### ISSUE TITLE
[Feature request] Evans in Docker

### ISSUE THREAD

**Issue by tarampampam** [ktr0731/evans#558]
Hi @ktr0731! Thanks for the awesome project!

Could you please provide a docker image with the Evans? You can use [GitHub Container Registry](https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-container-registry) for this or `hub.docker.com` (first is better) and GitHub actions for the images building & pushing into the registry. If you want, I can make a PR with all the required changes for this (and besides, I've already made [tarampampam/evans-docker](https://github.com/tarampampam/evans-docker), but image building on your side is much better).

**Comment by ktr0731** [comment]
Hi. It sounds good to publish Docker images. 
However, I think It is hard to maintain such a container repository continuously. This project is a personal project and the core maintainer is only me.
We distribute Evans to a lot of platforms such as macOS, Windows, and Linux via GitHub Releases. Given the aspect of maintenance cost and target platforms, I feel that it is better to build our own image for now. If lots of people want it, then we can consider it again.

**Comment by ktr0731** [comment]
Yes, it is easy to build Docker images. However, providing Docker images means also providing support for them.
For example, we need to support other platforms and resolve issues related to networking, container, or Docker itself. We are concerned about these potential problem.

**Comment by tarampampam** [comment]
> we need to support other platforms

Go supports multi-platform building out of the box, and here is a working example for the docker image:

```yaml
      - uses: docker/build-push-action@v3 # Action page: <https://github.com/docker/build-push-action>
        with:
          context: .
          file: Dockerfile
          push: true
          platforms: linux/386,linux/amd64,linux/arm64,linux/arm/v6 // <-- other platforms
```

> resolve issues related to networking, container, or Docker itself

Usually, usage examples provided in the readme file are enough. For example:

> You can use our docker image to run Evans. For example, if you want connect to the server on host `example.com` on port `50051` using proto file in `./path/to/dir/with/proto/files/file-name.proto`  (default working directory is `/mount`):
>
> ```shell
> $ docker run --rm -v "$(pwd):/mount:ro" \
>     ghcr.io/ktr0731/evans:latest \
>       --path ./path/to/dir/with/proto/files \
>       --proto file-name.proto \
>       --host example.com \
>       --port 50051 \
>       repl
> ```

Also, you can tag me to solve any docker issues 😄
